### ISSUE TITLE
[Beamer] Geschweifte Klammer in Code-Listing

### ISSUE THREAD

**Issue by fehrlich** [tud-cd/tud-cd#11]
Das tud-theme in der Beamer Klasse scheint geschweifte Klammern in Code-listings zu zerstören.

```Tex
\documentclass{beamer}

\usetheme{tud}
\usepackage{listings}

\begin{document}

\begin{frame}[fragile]{Test}
\begin{lstlisting}
block {
	Indent
}
\end{lstlisting}
\end{frame}

\end{document}
```

Als ergebnis wird im Listing

```
block -
	Indent
"
```
ausgegeben.

**Comment by keinstein** [comment]
Hallo,

ich kann das Verhalten bestätigen. Das scheint an den Fonts zu liegen. Wenn ich 

    \usepackage[T1]{fontenc}

verwende scheint es zu funktionieren.

[bug11.txt](https://github.com/tud-cd/tud-cd/files/34731/bug11.txt)
[bug11.pdf](https://github.com/tud-cd/tud-cd/files/34732/bug11.pdf)

ist das ein brauchbarer Workaround?

Aus verschiedenen Gründen würde ich Dir empfehlen, [diese Anleitung](https://github.com/tud-cd/tudscrold/releases/tag/fonts) mal auszuprobieren. Dann solltest Du dem TUD-Stil noch sagen, dass er die Beamer-Fonts verwenden soll:

    \usetheme[beamerfont]{tud}

Das Problem liegt darin, dass das Paket tudfonts die T1-Kodierung (8bit) voraussetzt, während Dein Beispiel nur OT1 (7bit) zur Verfügung hat. Da ich selbst jetzt kaum Zeit habe und es bessere Fonts gibt, habe ich momentan keine große Motivation tudfonts zu debuggen. Zielführender erscheint mir aber die Integration von tudscrfonts.

**Comment by fehrlich** [comment]
vielen Dank durch die Zeile

```
\usepackage[TS1,T1]{fontenc}
```

konnte ich es beheben
