### ISSUE TITLE
Beamer: // und , in Fußzeile

### ISSUE THREAD

**Issue by mfr13** [tud-cd/tud-cd#14]
Hallo,

die beamer-Vorlage im neuen CD ist wirklich sehr gut geworden. Eine Kleinigkeit stört jedoch:
- wenn weder `\einrichtung` noch `\fachrichtung` noch `\institut` noch `\professur` vorgegeben werden, dann erscheinen in der Fußzeile vor dem Autor dennoch die zwei Tennstriche //
-  ähnliches Problem besteht bei `\date` und `\datecity`, werden diese nicht vorgegeben erscheint trotzdem das Komma.

**Comment by keinstein** [comment]
Hallo mfr13,

ich kann das gerade nicht nachvollziehen. Kannst Du bitte ein Minimalbeispiel posten, das das demonstriert?

Welche TeX-Distribution verwendest Du auf welchem Betriebssystem?

**Comment by mfr13** [comment]
Hier mal ein Minimalbeispiel:
<pre><code>\documentclass[ngerman]{beamer}
\usepackage[utf8]{luainputenc}
\usepackage[TS1,T1]{fontenc}
\usepackage{babel}
\usetheme[pagenum,ddc]{tud}

\title{Titel}
\author{Autor}
\datecity{}
\einrichtung{}
\fachrichtung{}
\institut{}
\professur{}

\begin{document}

\maketitle

\begin{frame}{Test}
\end{frame}

\end{document}
</code></pre>

habe es mit MikTex unter Windows 8.1 gestestet.

**Comment by keinstein** [comment]
Danke. Das Datum habe ich korrigiert. Das // bekommst Du entsprechend dem Beamer-Standard mit \institute{} in der Präambel weg. Damit sparst Du auch das Setzen von Einrichtung, Fachrichtung, Institut und Professur.

**Comment by mfr13** [comment]
Perfekt, Danke.
