### ISSUE TITLE
if vs. ifx

### ISSUE THREAD

**Issue by stefborg** [tud-cd/tud-cd#21]
Seit commit [e91004f](https://github.com/tud-cd/tud-cd/commit/e91004f48327eb9b60a65a25b8eb4382e34e190e) ist die Fußzeile bei mir kaputt: Der Autor erscheint zweimal, und es gibt kein Trennzeichen zwischen Institut und Autor. Was war der Grund, \ifx durch \if zu ersetzen?

**Comment by keinstein** [comment]
\if wird expandiert, \ifx nicht.

Kannst Du bitte ein [Minimalbeispiel](http://www.minimalbeispiel.de/) posten?

Außerdem wäre ein Hinweis auf Deine TeX-Distribution hilfreich.

**Comment by stefborg** [comment]
Hier ein MWE:
```
\documentclass{beamer}
\usepackage[utf8]{inputenc}
\usepackage{textcomp}

\usetheme{tud}

\title{Titel}
\author[© Stefan Borgwardt]{Stefan Borgwardt}
\professur{Chair X}

\begin{document}
\begin{frame}
\end{frame}
\end{document}
```

Es scheint am Copyright-Zeichen zu liegen. Der Fehler tritt auch auf, wenn ich `\textcopyright` statt © schreibe, und auch ohne `\usepackage{textcomp}`, nur sieht das Zeichen dann anders aus.

Ich benutze mactex (texlive) 2015.

**Comment by keinstein** [comment]
Ich habe die beiden Argumente von \if mal eingeklammert. Jetzt scheint es auch bei pdflatex zu funktionieren (ich verwende inzwischen lualatex).

**Comment by stefborg** [comment]
Vielen Dank!
