### ISSUE TITLE
[cd2018] Titel unsichtbar

### ISSUE THREAD

**Issue by schmittlauch** [tud-cd/tud-cd#22]
Der Titeltext auf der ersten Folie existiert zwar (kann markiert werden), ist aber unsichtbar.

Ich vermute, dass dies ein Problem mit Fonts ist. Möglicherweise habe ich auch etwas falsch verstanden.

OpenSans habe ich aus meinen Distributions-Repos installiert, sodass die Font jetzt als .ttf s in `/usr/share/fonts/open-sans/` liegt.
Ich habe es so verstanden, dass mit dem 2018er CD keine anderen Fonts mehr benötigt werden. Dennoch bekomme ich von pdflatex olgende Warnung:
`Package beamerfontthemetud Warning: Neither package 'tudscrfonts' nor 'tudfonts
' was loaded! on input line 109.`

Brauche ich doch noch weitere Fonts? Interessanterweise hilft nicht einmal die Themeoption `beamerfont`, das Problem zu beheben (siehe unten).

Ich benutze, wie empfohlen, pdflatex zum kompilieren.

Auszüge meines Dokuments:

```latex
\documentclass[aspectratio=169]{beamer}
\mode<presentation>
{
  \usetheme[cd2018,beamerfont,noddc,navbar]{tud}
}

\usepackage[english]{babel}

\usepackage[latin1]{inputenc}

\usepackage{times}
\usepackage[T1]{fontenc}
% Or whatever. Note that the encoding and the font should match. If T1
% does not look nice, try deleting the line with the fontenc.

\title[short]{loooooooooooooooooooooooooooooooong}

\subtitle
{Include Only If Paper Has a Subtitle}

\author
{John Doe}

\institute[] % (optional, but mostly needed)
{
  Department of Computer Science\\
  Technical University Dresden
}

\date[FOO2018] % (optional, should be abbreviation of conference name)
{FooCon 18}

\subject{Theoretical Computer Science}
\AtBeginSubsection[]
{
  \begin{frame}<beamer>{Outline}
    \tableofcontents[currentsection,currentsubsection]
  \end{frame}
}

\begin{document}

\begin{frame}
  \titlepage
\end{frame}

\begin{frame}{Outline}
  \tableofcontents
\end{frame}
\end{document}
```

**Comment by keinstein** [comment]
Hast Du konkrete Vorschläge/Formulierungen/Patches?
