### ISSUE TITLE
Beamer: Konflikt mit Paket "menukeys"

### ISSUE THREAD

**Issue by fer-rum** [tud-cd/tud-cd#25]
### Problem
Wenn ich versuche, das Beamer-theme zusammen mit dem Paket [_menukeys_](https://www.ctan.org/pkg/menukeys) zu verwenden, bekomme ich die Fehlermeldung

```
(./tudcolors.sty
! LaTeX Error: Option clash for package xcolor.                                                               
l.36 \@ifundefined
                  {tudcolor@model}{}{%
? h
The package 'xcolor' has already been loaded with options:
  [natural].
```

### Minimum example
```latex
\documentclass{beamer}

\usepackage{menukeys}

\usetheme[pagenum, beamerfont]{tud}

\title{Bug Reports 101}
\author{Fredo Erxleben}
\date{\today}

\begin{document}
    \maketitle
\end{document}
```

### Workaround
Auskommentieren von __tudcolors.sty__ Zeile 33:
```latex
%  \PassOptionsToPackage{natural}{xcolor}%
```
behebt das Problem. Einen Unterschied im Farbschema des Dokuments war dabei nicht festzustellen.

**Comment by keinstein** [comment]
Aus der menukeys-Doku.
> menukeys must be loaded after xcolor, if you load the latter with options. Otherwise you’ll get an option clash Since menukeys loads xcolor internally you may pass options as global options via \documentclass.

Oder halt mit `\PassOptionsToPackage`


Klingt für mich so, als ob Du menukeys nach `\usetheme` laden musst.

Hilft Dir 
```
    \PassOptionsToPackage{natural}{xcolor}%
```
vor dem Laden von menukeys?

Das Problem ist, dass die Umrechnung des Farbmodells nicht wirklich gut funktioniert. Tudcolors definiert Farben in RGB (für Bildschirme) und CMYK (zum drucken). Natural sollte unkonvertiert das RGB-Modell verwenden. Willst Du etwas anderes, dann musst Du das tudcolors sagen.

**Comment by fer-rum** [comment]
Das Theme vor den Packages zu laden hilft. Danke.
