### ISSUE TITLE
Beamerpräsentation tudcolor.sty not found

### ISSUE THREAD

**Issue by Johannes0791** [tud-cd/tud-cd#32]
Hej,
ich versuche mit den mir zu Verfügung stehenden Ressourcen eine Präsentation zu erstellen.
Also mit dem neuen CD der TU Dresden. 

Leider taucht bei mir immer der Fehler "'tudcolor.sty' not found" auf. Gibt es da eine Lösung?
Als Beispiel und "Starthilfe" habe ich die tex-datei "beamer-org-mode-demo.tex" kopiert.

Das aktuelle tudscr ist installiert. Auch alle sonstigen Beamerthemes stehen zur Verfügung. 
Ich benutze MikTex und Texmaker

**Comment by keinstein** [comment]
Du hast anscheinend nicht das gesamte tud-cd installiert. Die gesuchte Datei gehört zu tudmathposter.

**Comment by Johannes0791** [comment]
Hej, danke für den Hinweis.
hat sich allerdings schon geklärt. Das Package lag nur an einem "falschen Ort".
Mein Fehler. Jetzt funks.
