### ISSUE TITLE
Ein- und Ausblenden von Grafiken mit \pause und \includegraphics<x-y>[..]{..}

### ISSUE THREAD

**Issue by wspalteholz** [tud-cd/tud-cd#41]
Hallo Liebe LaTeX-Gemeinde der TU,

ich erstelle bereits sehr lange Zeit Folien in der Beamer-Klasse. Nun wollte ich diese endlich mal unter Verwendung der Vorlage an das CD des TU anpassen.

Leider habe ich folgendes Problem: Ich nutze häufig das Einblenden von Textpassagen mittels \pause. Dazu ändere ich häufig in einem bestimmten Bereich der Folie das dazu angezeigte Bild. 

Folgendes Beispiel und das Bild _1.png_ erläutern das:

```
\begin{itemize}
	\pause\item \imp{Mails} signieren \newline (Die Mail ist wirklich von mir und der Inhalt unverfälscht) \erinn{$\rightarrow$ Ausweiskontrolle}
	\pause\item \imp{Mails} verschlüsseln \newline (Niemand außer dem Empfänger kann die Mail lesen) \erinn{$\rightarrow$ Schlüsseltauschproblem}
	\pause\item \imp{PDF-Dokumente} digital signieren (unterschreiben) \erinn{$\rightarrow$ Ausweiskontrolle}
\end{itemize}
\begin{center}
	\includegraphics<2>[width=0.5\textwidth]{bilder/signiert} 
	\includegraphics<3>[width=0.5\textwidth]{bilder/asymm} 
	\includegraphics<4->[width=0.5\textwidth]{bilder/unterschrieben}
\end{center}

```
Verwende ich die  TU-Vorlage wird jeweils nur das letzte Bild angezeigt (vgl. _2.png_).

Gibt es daraus einen Ausweg? Ich bin sehr wohl gewillt das CD der TU zu nehmen, kann aber unmöglich alle meine Präsentationen komplett umformulieren.

Es Dankt,

W. Spalteholz 
<img width="465" alt="1" src="https://user-images.githubusercontent.com/74537367/183673543-2681bde7-33ee-41ce-8562-eac9a83b2901.png">
<img width="474" alt="2" src="https://user-images.githubusercontent.com/74537367/183673555-ebeb3030-722f-44a0-83e1-5344a42814c0.png">

**Comment by keinstein** [comment]
Hallo @wspalteholz 

kannst Du bitte mal ein vollständiges Beispiel posten (gern auch 2 Minimalbeispiele: https://www.minimalbeispiel.de/), dann
lässt sich das Problem viel besser  debuggen. Ich habe auch viel mit Animationen gearbeitet und es hat immer geklappt.
Allerdings verwende ich in diese Situation immer `\item<+->` und nicht \pause.

Viele Grüße
Tobias Schlemmer

**Comment by wspalteholz** [comment]
Lieber Tobias Schlemmer,

es war mein Fehler: Durch die Umstellung auf das TU-CD habe ich (natürlich) viele meiner eigenen Einstellungen über Bord geworfen. Dabei ging schlicht das 
`\setbeamercovered{transparent}`
mit verloren. Genau das wird aber für meinen Anwendungsfall benötigt.

Vielen Dank!

W. Spalteholz
