### ISSUE TITLE
Beamer: \institut , \einrichtung  und \professur werden nicht angezeigt

### ISSUE THREAD

**Issue by thfr** [tud-cd/tud-cd#9]
Hallo,

erstmal herzlich Dank für die überarbeitete Version der Beamer Vorlage. Wie der Titel des Issues zeigt, werden funktionieren die Befehle für das Professur, des Instituts und der Einrichtung bzw. Fakultät nicht. 

@keinstein  In deinem hochgeladen Beispieldokument funktioniert es selbst nicht, siehe https://github.com/tud-cd/tud-cd/blob/master/beamer-org-mode-demo.pdf , obwohl  

``` latex
\institut{Institut f\"ur Algebra}%
```

angegeben wurde. Die anderen haben in meinen Tests auch nicht funktioniert.

PS: Da es kein TexLive-Paket für "uniinput.sty", sollte es vielleicht mit Repo aufgenommen werden. Habe es [hier](http://wiki.neo-layout.org/attachment/ticket/317/uniinput.sty) gefunden.

**Comment by keinstein** [comment]
Danke für den Hinweis. Jetzt sollte es gehen. Das vorherige Verhalten kann man mit 

    \setbeamertemplate{einrichtung/titlepage}{empty}
    \setbeamertemplate{fachrichtung/titlepage}{empty}
    \setbeamertemplate{institut/titlepage}{empty}
    \setbeamertemplate{professur/titlepage}{empty}

wiederherstellen. Es ist allerdings noch nicht dokumentiert.
